version: '3.9'
services:

  postgres:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_USER: "wallet"
      POSTGRES_PASSWORD: "wallet"
      POSTGRES_DB: "wallet"
    ports:
      - "5432:5432"
